[paths]
# Root directory where Lab Files live (sample you showed uses files like "C9359766")
#labfile_root = 'C:\Users\gilli\Projects\XcelSpecialtyContacts\Optimum_Infinite_Orthokeratology_Lens_II\test_xcelftp'
#labfile_root = 'D:\Projects\XcelSpecialtyContacts\Optimum_Infinite_Orthokeratology_Lens_II\test_xcelftp'
labfile_root = 'T:\'

[output]
#dir = 'C:\Users\gilli\Projects\XcelSpecialtyContacts\Optimum_Infinite_Orthokeratology_Lens_II\test_dacfiles'
dir = 'D:\Projects\XcelSpecialtyContacts\Optimum_Infinite_Orthokeratology_Lens_II\test_dacfiles'
file_stem_pattern = '{wo}_{surface}'  # {surface} in {'anterior','interior'}
# A flexible line format so you can match DAC ALM easily (change spacing/precision if needed)
point_format = '{x:.4f}\t{z:.4f}'
header = '# WO={wo} SURFACE={surface} MERIDIAN={theta}\n# X(mm)\tZ(mm)\n'
footer = ''

[xcel.pointfile_parms]
point_spacing_mm = 0.010   # spacing along meridian between points
meridians = 4              # e.g., 0°,90°,180°,270° (two flat, two steep)

[xcel.options]
use_vertex_code_from_lab = true  # if false, override below
vertex_code = 2                  # 1=BVP, 2=FVP
